name: Generate Pac-Man Animation

# O workflow será executado:
on:
  # 1. Automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  # 2. Manualmente pela interface do Actions
  workflow_dispatch:
  # 3. Sempre que houver um push para o branch 'main'
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write # Permite que o workflow escreva no repositório
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate pacman-contribution-graph.svg
        # Esta ação irá criar a imagem SVG no diretório /dist
        uses: abozanona/pacman-contribution-graph@main
        with:
          # O nome de usuário é capturado automaticamente (santtitoz)
          github_user_name: ${{ github.repository_owner }}


      - name: Push pacman-contribution-graph.svg to the output branch
        # Esta ação pega a imagem gerada e a salva no branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Define o branch onde a imagem será salva
          target_branch: output 
          # Define o diretório onde a imagem foi gerada (padrão da ação)
          build_dir: dist 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
